
  export const pageTitles = {
    "patienttable": "Patients",
    "patientdata": "Patient Treatment",
    "patientglobal": "Patient Details",
    "newleadinfo": "Leads",
    "appointments_2": "Scheduler",

    "account": "Account Settings",
    "account/profile-settings": "Profile Settings",
    "account/personal-information": "Personal Information",
    "account/clinic-information": "Clinic Information",
    "account/request-invite-new-company": "Request/Invite Company",
    "account/consultation-templates": "Consultation Templates",
    "account/communication-templates": "Communication Templates",
    "account/user-management": "User Management",
    "account/dental-components-management": "Dental Components Management",
    "account/medication-management": "Medication Management",
    "account/clinlog-management": "Clinlog Management",
    "account/mas-information": "MAS Information",
    "account/mas-user-management": "MAS User Management",
    "account/laboratory-information": "Laboratory Information",
    "account/laboratory-user-management": "Laboratory User Management",
    "account/teeth-brand-moulds": "Teeth Brand/Moulds",
    "account/help-guides": "Help Guides",
    "account/internal-news": "Internal News",
    "account/resources": "Resources",
    "account/branding": "Branding",
    "account/patient-terms": "Patient Terms & Conditions",
    "account/staff-terms": "Staff Terms & Conditions",
    "account/appearance": "Appearance",
    "account/tags": "Tags",
    "account/billing": "Billing",

    "dashboard": "Dashboard",
    "tools": "Tools",
    "tools/Campaigns": "Campaigns",
    "tools/CDMTable": "CDM Table",
    "tools/DmagTool": "DMAG Tool",
    "tools/Invoices": "Invoices",
    "tools/Reports": "Reports",

    "viewer": "Form Viewer",

    "privacy": "Privacy Policy",
    "sensitive-information": "Sensitive Information",
    "terms": "Terms and Conditions",

    "support": "Support",
  }